name: 404 links

# currently disabled based on https://github.com/restqa/404-links/issues/4

#on: [push]
#
#jobs:
#  check-links:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: 'restqa-404-links'
#      uses: restqa/404-links@1.0.0
#      with:
#        path: 'docs'
